// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyefnhumlvruazuyzzou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5ZWZuaHVtbHZydWF6dXl6em91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MTg3MjEsImV4cCI6MjA2MTk5NDcyMX0.rwgaaVKy6K9hiBRqtQgKPQl9lBU_LSdFSVh-TtHm7j8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);